% DataPreprocessRunAll
%
% Run data proprocessing over the whole data set, extracting just
% the variables of interest after any massaging that is necessary.
%
% 3/25/14  dhb  Wrote it.
% 4/15/16  dhb  Now this is just data preprocessing.

% Clear
clear; close all;

%% Make sure we're running from our directory
myDir = fileparts(mfilename('fullpath'));
cd(myDir);

%% Set path
SetAnalysisPath;

%% Compute or just plot?
runAllCompute = true;

%% Original paint/shadow
% 
DataPreprocessRunOne(...
    'dataType','spksrt', ...
    'type','aff', ...
    'classifyType','mvma', ...
    'rfAnalysisType','no', ...
    'pcaType','no', ...
    'trialShuffleType','notshf', ...
	'paintShadowShuffleType','nopsshf', ...    
    'decodeIntensityFitType','betacdf', ...
    'paintCondition', 1, ...
    'shadowCondition', 2, ...
    'paintShadowFitType', 'intcpt',  ...
    'excludeSYelectrodes','sykp', ...
    'minTrials',5, ...
    'filterRangeLower',0.2, ...
    'doIndElectrodeRFPlots',true, ...
    'reallyDoIRFPlots',false, ...
    'reallyDoRFPlots',false, ...
    'COMPUTE', runAllCompute, ...
    'plotV4Only', false, ...
    'DATASTYLE', 'new' ...
    );
close all



