% RunAllConditions
%
% Do the whole kit and kaboodle of decoding analyses
%
% 3/25/14  dhb  Wrote it.

% Clear
clear; close all;

%% Make sure we're running from our directory
myDir = fileparts(mfilename('fullpath'));
cd(myDir);

%% Set path
SetAnalysisPath;

%% V4 only?
runAllPlotV4Only = false;

%% Compute or just plot?
runAllCompute = false;

%% Datastyle
DATASTYLE = 'new';

%% Original paint/shadow
% 
% Was running rfAnalysisType 'std'
RunOneCondition(...
    'dataType','spksrt', ...
    'type','aff', ...
    'classifyType','mvma', ...
    'rfAnalysisType','no', ...
    'pcaType','no', ...
    'decodeJoint','both', ...
    'decodeOffset',0, ...
    'trialShuffleType','notshf', ...
	'paintShadowShuffleType','nopsshf', ...    
    'decodeIntensityFitType','betacdf', ...
    'paintCondition', 1, ...
    'shadowCondition', 2, ...
    'paintShadowFitType', 'intcpt',  ...
    'looType', 'no', ...
    'classLooType', 'no', ...
    'excludeSYelectrodes','sykp', ...
    'errType', 'mean', ...
    'minTrials',20, ...
    'filterRangeLower',0.2, ...
    'doIndElectrodeRFPlots',true, ...
    'reallyDoIRFPlots',false, ...
    'reallyDoRFPlots',false, ...
    'COMPUTE', runAllCompute, ...
    'plotV4Only', runAllPlotV4Only, ...
    'DATASTYLE', DATASTYLE ...
    );
close all

% %% PCA
% for pcaKeep = [5 10 15 20]
%     RunOneCondition(...
%         'dataType','spksrt', ...
%         'type','aff', ...
%         'classifyType','mvma', ...
%         'rfAnalysisType','no', ...
%         'pcaType','sdn', ...
%         'pcaKeep',pcaKeep, ...
%         'decodeJoint','both', ...
%         'decodeOffset',0, ...
%         'trialShuffleType','notshf', ...
%         'paintShadowShuffleType','nopsshf', ...
%         'decodeIntensityFitType','betacdf', ...
%         'paintCondition', 1, ...
%         'shadowCondition', 2, ...
%         'paintShadowFitType', 'intcpt',  ...
%         'looType', 'no', ...
%         'classLooType', 'no', ...
%         'excludeSYelectrodes','sykp', ...
%         'errType', 'mean', ...
%         'minTrials',20, ...
%         'filterRangeLower',0.2, ...
%         'doIndElectrodeRFPlots',true, ...
%         'reallyDoIRFPlots',false, ...
%         'reallyDoRFPlots',false, ...
%         'COMPUTE', runAllCompute, ...
%         'plotV4Only', runAllPlotV4Only, ...
%         'DATASTYLE', DATASTYLE ...
%         );
%     close all
% end
% 
% %% Best two electrodes
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','mvma', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','bothbestdouble', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'no', ...
%     'classLooType', 'no', ...
%     'excludeSYelectrodes','sykp', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only, ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all

% %% Best single electrode
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','mvma', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','bothbestsingle', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'no', ...
%     'classLooType', 'no', ...
%     'excludeSYelectrodes','sykp', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only, ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all

% Basic affine decoding on paint with one trial LOO.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','paint', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only, ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Basic affine decoding on shadow with one trial LOO.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','shadow', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only, ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all

% % Maximum likelihood decoding, none left our for debugging.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','mlbayes', ...
%     'classifyType','no', ...
%     'rfAnalysisType','std', ...
%     'pcaType','no', ...
%     'decodeJoint','both', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',false, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Basic affine decoding with one trial LOO.
% % This time with an offset
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','std', ...
%     'pcaType','no', ...
%     'decodeJoint','both', ...
%     'decodeOffset',06, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', false, ...
%     'plotV4Only', runAllPlotV4Only ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Basic affine decoding with trial shuffle.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','both', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','intshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Best single electrode
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','std', ...
%     'pcaType','no', ...
%     'decodeJoint','bothbestsingle', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'no', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',true, ...
%     'reallyDoRFPlots',true, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Best two electrodes
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','no', ...
%     'rfAnalysisType','no', ...
%     'pcaType','no', ...
%     'decodeJoint','bothbestdouble', ...
%     'decodeOffset',0, ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'no', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'doIndElectrodeRFPlots',true, ...
%     'reallyDoIRFPlots',false, ...
%     'reallyDoRFPlots',false, ...
%     'COMPUTE', runAllCompute, ...
%     'plotV4Only', runAllPlotV4Only ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% for pcaKeep = [30 20 15 10 5]
%     RunOneCondition(...
%         'dataType','spksrt', ...
%         'type','aff', ...
%         'classifyType','nnh', ...
%         'rfAnalysisType','no', ...
%         'pcaType','sdn', ...
%         'pcaKeep',pcaKeep, ...
%         'decodeJoint','both', ...
%         'decodeOffset',0, ...
%         'trialShuffleType','notshf', ...
%         'paintShadowShuffleType','nopsshf', ...
%         'decodeIntensityFitType','betacdf', ...
%         'paintCondition', 1, ...
%         'shadowCondition', 2, ...
%         'paintShadowFitType', 'intcpt',  ...
%         'looType', 'ot', ...
%         'errType', 'mean', ...
%         'minTrials',20, ...
%         'filterRangeLower',0.2, ...
%         'doIndElectrodeRFPlots',true, ...
%         'reallyDoIRFPlots',true, ...
%         'reallyDoRFPlots',true, ...
%         'COMPUTE', runAllCompute, ...
%         'plotV4Only', runAllPlotV4Only, ...
%         'DATASTYLE', DATASTYLE ...
%         );
%     close all
% end

% 
% return
% 
% % Basic affine pca decoding with one trial LOO.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'classifyType','libsvmsvm', ...
%     'classifyReduce','', ... %'classifyReduce','ignoredecode', ...
%     'pcaType','sdn', ...
%     'pcaKeep',30, ...
%     'rfAnalysisType','no', ...
%     'decodeJoint','both', ...
%     'trialShuffleType','notshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'COMPUTE', true ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% % Basic affine decoding with trial shuffle.
% RunOneCondition(...
%     'dataType','spksrt', ...
%     'type','aff', ...
%     'decodeJoint','both', ...
%     'trialShuffleType','intshf', ...
% 	'paintShadowShuffleType','nopsshf', ...    
%     'decodeIntensityFitType','betacdf', ...
%     'paintCondition', 1, ...
%     'shadowCondition', 2, ...
%     'paintShadowFitType', 'intcpt',  ...
%     'looType', 'ot', ...
%     'errType', 'mean', ...
%     'minTrials',20, ...
%     'filterRangeLower',0.2, ...
%     'COMPUTE', true ...
%     'DATASTYLE', DATASTYLE ...
%     );
% close all
% 
% %% Shuffled Conditions
% RunShuffleConditions;

