% RunAllConditions
%
% Do the whole kit and kaboodle of decoding analyses
%
% 3/25/14  dhb  Wrote it.

% Clear
clear; close all;

%% Make sure we're running from our directory
myDir = fileparts(mfilename('fullpath'));
cd(myDir);

%% Set path
SetAnalysisPath;

%% V4 only?
runAllPlotV4Only = false;

%% Compute or just plot?
runAllCompute = true;

%% Datastyle
DATASTYLE = 'new';

%% Original paint/shadow
% 
% Was running rfAnalysisType 'std'
RunOneCondition(...
    'dataType','spksrt', ...
    'type','aff', ...
    'classifyType','mvma', ...
    'rfAnalysisType','no', ...
    'pcaType','no', ...
    'decodeJoint','both', ...
    'decodeOffset',0, ...
    'trialShuffleType','notshf', ...
	'paintShadowShuffleType','nopsshf', ...    
    'decodeIntensityFitType','betacdf', ...
    'paintCondition', 1, ...
    'shadowCondition', 2, ...
    'paintShadowFitType', 'intcpt',  ...
    'decodeLOOType', 'no', ...
    'classdecodeLOOType', 'no', ...
    'excludeSYelectrodes','sykp', ...
    'errType', 'mean', ...
    'minTrials',20, ...
    'filterRangeLower',0.2, ...
    'doIndElectrodeRFPlots',true, ...
    'reallyDoIRFPlots',false, ...
    'reallyDoRFPlots',false, ...
    'COMPUTE', runAllCompute, ...
    'plotV4Only', runAllPlotV4Only, ...
    'DATASTYLE', DATASTYLE ...
    );
close all



