% SummarizeRunAll
%
% Collect up the extracted data analyses of individual conditions and make
% summary plots.
%
% 3/25/14  dhb  Wrote it.

% Clear
clear; close all;

%% Specify which analsyses to do

%% Make sure we're running from our directory
myDir = fileparts(mfilename('fullpath'));
cd(myDir);

%% Original paint/shadow
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectAff,repSimAff,RMSEAnalysisAff,RMSEVersusNUnitsAff,RMSEVersusNPCAAff,ClassificationVersusNUnitsAff,ClassificationVersusNPCAff] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','maxlikely', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectML,repSimML,RMSEAnalysisML,RMSEVersusNUnitsML,RMSEVersusNPCAML, ClassificationVersusNUnitsML, ClassificationVersusNPCML] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli fano decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','maxlikelyfano', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLF,repSimMLF,RMSEAnalysisMLF,RMSEVersusNUnitsMLF,RMSEVersusNPCAMLF, ClassificationVersusNUnitsMLF, ClassificationVersusNPCMLF] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli mean variance decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','maxlikelymeanvar', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLMV,repSimMLMV,RMSEAnalysisMLMV,RMSEVersusNUnitsMLMV,RMSEVersusNPCAMLMV, ClassificationVersusNUnitsMLMV, ClassificationVersusNPCMLMV] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli Poisson variance decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','maxlikelypoiss', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLP,repSimMLP,RMSEAnalysisMLP,RMSEVersusNUnitsMLP,RMSEVersusNPCAMLP, ClassificationVersusNUnitsMLP, ClassificationVersusNPCMLP] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli Bayes decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','mlbayes', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLB,repSimMLB,RMSEAnalysisMLB,RMSEVersusNUnitsMLB,RMSEVersusNPCAMLB, ClassificationVersusNUnitsMLB, ClassificationVersusNPCMLB] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli Bayes fano decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','mlbayesfano', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLBF,repSimMLBF,RMSEAnalysisMLBF,RMSEVersusNUnitsMLBF,RMSEVersusNPCAMLBF, ClassificationVersusNUnitsMLBF, ClassificationVersusNPCMLBF] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli Bayes mean variance decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','mlbayesmeanvar', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLBMV,repSimMLBMV,RMSEAnalysisMLBMV,RMSEVersusNUnitsMLBMV,RMSEVersusNPCAMLBMV, ClassificationVersusNUnitsMLBMV, ClassificationVersusNPCMLBMV] = SummarizeRunOne(argList{:});
close all

%% Original paint/shadow, max likeli Bayes Poisson variance decoder
argList = SetupConditionArgs('basic');
argList = {argList{:}, ...
    'type','mlbayespoiss', ...
    'doSummaryPaintShadowEffect',true, ...
    'doSummaryRepSim',false, ...
    'doSummaryRMSEAnalysis',false, ...
    'doSummaryRMSEVersusNUnits',false, ...
    'doSummaryRMSEVersusNPCA',true, ...
    'doSummaryClassificationVersusNUnits',false, ...
    'doSummaryClassificationVersusNPCA',false, ...
    };
[paintShadowEffectMLBP,repSimMLBP,RMSEAnalysisMLBP,RMSEVersusNUnitsMLBP,RMSEVersusNPCAMLBP, ClassificationVersusNUnitsMLBP, ClassificationVersusNPCMLBP] = SummarizeRunOne(argList{:});
close all

%% Make a plot of RMSE for affine versus ML decoder
tempBothAff = [paintShadowEffectAff.decodeBoth];
tempBothMLBMV = [paintShadowEffectMLBMV.decodeBoth];
figure; clf; hold on
plot([RMSEVersusNPCAAff.bestRMSE],[RMSEVersusNPCAMLMV.bestRMSE],'ko','MarkerSize',6,'MarkerFaceColor','k');
plot([RMSEVersusNPCAAff.bestRMSE],[RMSEVersusNPCAMLF.bestRMSE],'ro','MarkerSize',6,'MarkerFaceColor','r');
plot([RMSEVersusNPCAAff.bestRMSE],[RMSEVersusNPCAMLBP.bestRMSE],'go','MarkerSize',6,'MarkerFaceColor','g');
plot([RMSEVersusNPCAAff.bestRMSE],[RMSEVersusNPCAMLP.bestRMSE],'bo','MarkerSize',6,'MarkerFaceColor','b');
%plot([tempBothAff.paintRMSE],[tempBothMLBMV.paintRMSE],'ro','MarkerSize',6,'MarkerFaceColor','r');
%plot([tempBothAff.shadowRMSE],[tempBothMLBMV.shadowRMSE],'bo','MarkerSize',6,'MarkerFaceColor','b');
plot([0 0.4],[0 0.4],'k:')
axis('square');
xlim([0 0.4]);
ylim([0 0.4]);
xlabel('Linear Decoder RMSE');
ylabel('Nonlinear Decoder RMSE')
title('Non-Linear Decoders');
