% SummarizeRunAll
%
% Collect up the extracted data analyses of individual conditions and make
% summary plots.
%
% 3/25/14  dhb  Wrote it.

% Clear
clear; close all;

%% Make sure we're running from our directory
myDir = fileparts(mfilename('fullpath'));
cd(myDir);

%% Set path
SetAnalysisPath;

%% Original paint/shadow
SummarizeRunOne(...
    'dataType','spksrt', ...
    'type','aff', ...
    'classifyType','mvma', ...
    'rfAnalysisType','no', ...
    'pcaType','no', ...
    'trialShuffleType','notshf', ...
	'paintShadowShuffleType','nopsshf', ...    
    'decodeIntensityFitType','betacdf', ...
    'paintCondition', 1, ...
    'shadowCondition', 2, ...
    'paintShadowFitType', 'intcpt',  ...
    'excludeSYelectrodes','sykp', ...
    'minTrials',20, ...
    'filterRangeLower',0.2, ...
    'doIndElectrodeRFPlots',true, ...
    'reallyDoIRFPlots',false, ...
    'reallyDoRFPlots',false, ...
    'COMPUTE', true, ...
    'plotV4Only', false, ...
    'DATASTYLE', 'new' ...
    );
close all

